source 'https://github.com/CocoaPods/Specs.git'
project 'Example.xcodeproj'
platform :ios, '10.0'

# ignore all warnings from all pods
inhibit_all_warnings!

use_frameworks!

def shared_pods
    pod 'SwiftyBeaver', '1.4.2'
end

def ui_pods
    pod 'ReactiveCocoa', '7.2.0'
end

def dependency_pods
    pod 'SalemoveSDK', :path => '../'
end

target 'Example' do
    shared_pods
    dependency_pods
    ui_pods
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'Socket.IO-Client-Swift'
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '3'
            end
        end

        if target.name == 'ReactiveCocoa'
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.0'
            end
        end
        
        target.build_configurations.each do |config|
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
        end
    end
end

