source 'https://github.com/CocoaPods/Specs.git'
project 'Example.xcodeproj'
platform :ios, '10.0'

# ignore all warnings from all pods
inhibit_all_warnings!

use_frameworks!

def ui_pods
    pod 'ReactiveCocoa', '8.0.2'
end

def dependency_pods
    pod 'SalemoveSDK', :path => '../'
end

target 'Example' do
    dependency_pods
    ui_pods
end

post_install do |installer|
    installer.pods_project.targets.each do |target|

        target.build_configurations.each do |config|
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
        end
    end
end
