source 'https://github.com/CocoaPods/Specs.git'
project 'ExampleApp.xcodeproj'
platform :ios, '10.0'

# ignore all warnings from all pods
inhibit_all_warnings!

use_frameworks!

target 'ExampleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ExampleApp
  pod 'SalemoveSDK', :path => '../'
  pod 'SwiftyBeaver', '1.8.4'
end
